#import csv
import openpyxl.styles

from openpyxl import load_workbook

from openpyxl import Workbook
#from openpyxl.compat import range
from openpyxl.utils import get_column_letter
from openpyxl.styles import PatternFill, Border, Side, Alignment, Protection, Font


#***************************************************
#               FEYZ                             KHARAZI  
#       [0-OFFICE_NAME,1-BIG-NODE,2-NODE-ID,3-OFFICE-ID,4-TREE,5-NEWDAS,6-SPCU,7-SPCSU,8-CMPMOD,9-ASID,10-copytree,delprf]
officel=[["FEYZ",10,17,210,1,200,99,2,13,20,396,33730000],["KHARAZI",20,27,400,201,800,98,3,13,27,850,33128]]


f = open("Commands.txt", "w")

al = Alignment(horizontal="center", vertical="center")
ft1 = Font(name='Calibri',size=16)


wb1 = load_workbook(filename = 'par.xlsx')
ws1 = wb1.active

prf = str(ws1.cell(row=2, column=2).value)

lis = str(ws1.cell(row=2, column=3).value).split('-')
min1=lis[0]
max1=lis[1]

tkgtype = str(ws1.cell(row=3, column=2).value)

callid= str(ws1.cell(row=4, column=2).value)

lis = str(ws1.cell(row=4, column=3).value).split('-')
min2=lis[0]
max2=lis[1]

tkg = str(ws1.cell(row=5, column=2).value)

tkgname = str(ws1.cell(row=6, column=2).value)

lis = str(ws1.cell(row=7, column=2).value).split('-')
ra = lis[0]
se = lis[1]
sl = lis[2]
su = lis[3]

lis = str(ws1.cell(row=8, column=2).value).split('-')
mod = lis[0]
unt = lis[1]


dch = str(ws1.cell(row=9, column=2).value)

office = int(ws1.cell(row=10, column=2).value)

offname=str(officel[office][0])
bignode=str(officel[office][1])
nodeid=str(officel[office][2])
officeid=str(officel[office][3])
tree=str(officel[office][4])
newdas=str(officel[office][5])
spcunit=str(officel[office][6])
spcsubu=str(officel[office][7])
cmpmod=str(officel[office][8])
asid=str(officel[office][9])
copytree=str(officel[office][10])
delprf=str(officel[office][11])

print(prf,min1,max1,tkgtype,callid,min2,max2,tkg,tkgname,ra,se,sl,su ,mod,unt,dch)
print(offname,bignode,nodeid,officeid,tree,newdas,spcunit,spcsubu,cmpmod)

#f.write("{0},{1},{2},{3},{4},{5},{6},{7},{8},{9},{10},{11},{12},{13},{14},{}\n".format())
f.write("{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{}\n".format(prf,min1,max1,tkgtype,callid,min2,max2,tkg,tkgname,ra,se,sl,su ,mod,unt,dch))
f.write("{},{},{},{},{},{},{},{},{}\n".format(offname,bignode,nodeid,officeid,tree,newdas,spcunit,spcsubu,cmpmod))

#**************************************************************
remark=tkg+"-PRA-"+tkgname+"("+prf+")"
ofcname="PRA-"+tkgname+"("+prf+")"
linkname="PRA-"+ prf

tidname='P'+("000"+mod)[-3:]+"00000"+("000"+unt)[-3:]+("000"+su)[-3:]

print(remark,ofcname,linkname,tidname)
f.write("{0},{1},{2},{3}\n".format(remark,ofcname,linkname,tidname))


#*MSG *********************************************************************************
print("\n***********************************************************\n")
print("*          1- MSG "+offname+"                                    *\n")
print("***********************************************************\n")

#print("MODIFY_DT_SUNIT:SUBSYSTEM=0,Unit="+unt+",SUNIT="+su+",SUNITTYPE=97,LINETYPE=0,Q50TAG=0,DCMEWORKMODE=0,OFCNO="+tkg+",OFCNAME=\""+ofcname+"\";")
print("MODIFY_DT_SUNIT:SUBSYSTEM=0,SUNITTYPE=97,Unit="+unt+",SUNIT="+su+",OFCNO="+tkg+",OFCNAME=\""+ofcname+"\",LINETYPE=0,Q50TAG=0,DCMEWORKMODE=0;")
print("ADD_PRI_DCHANEL:DLINK="+dch+",MODULE="+cmpmod+",INFO=0,INFO1=2,DLINKNAME=\""+linkname+"\";")
print("MODIFY_PHLK:LINK="+dch+",LINKTYPE=3,SUBSYSTEM=0,SPBUNIT="+spcunit+",CPUID="+spcsubu+",TRKSUBSYS=0,TRKUNIT="+unt+",TRKE1="+su+",TRKSTARTTS=16,TSNUM=1,INFO=0,INFO1=2,COSPBUNIT=0,COCPUID=0,DLINKNAME=\""+linkname+"\";")
print("ADD_LINKAS:LINKNO="+dch+",LINKTYPE=3,ASID="+asid+",LINKID="+dch+";")
print("ASSIGN_TERMID:SUBSYSTEM=0,MODULE="+mod+",MGID=1,RESKIND=1,UNIT="+unt+",SUNIT_ST="+su+",SUNIT_END="+su+",BTIDNAME=\"P\";")
print("\n")

f.write("\n***********************************************************\n")
f.write("*          1- MSG {}                                    *\n".format(offname))
f.write("***********************************************************\n\n")

f.write("MODIFY_DT_SUNIT:SUBSYSTEM=0,SUNITTYPE=97,Unit={0},SUNIT={1},OFCNO={2},OFCNAME=\"{3}\",LINETYPE=0,Q50TAG=0,DCMEWORKMODE=0;\n".format(unt,su,tkg,ofcname))
f.write("ADD_PRI_DCHANEL:DLINK={0},MODULE={1},INFO=0,INFO1=2,DLINKNAME=\"{2}\";\n".format(dch,cmpmod,linkname))
f.write("MODIFY_PHLK:LINK={0},LINKTYPE=3,SUBSYSTEM=0,SPBUNIT={1},CPUID={2},TRKSUBSYS=0,TRKUNIT={3},TRKE1={4},TRKSTARTTS=16,TSNUM=1,INFO=0,INFO1=2,COSPBUNIT=0,COCPUID=0,DLINKNAME=\"{5}\";\n"
.format(dch,spcunit,spcsubu,unt,su,linkname))

f.write("ADD_LINKAS:LINKNO={},LINKTYPE=3,ASID={},LINKID={};\n".format(dch,asid,dch))
f.write("ASSIGN_TERMID:SUBSYSTEM=0,MODULE={0},MGID=1,RESKIND=1,UNIT={1},SUNIT_ST={2},SUNIT_END={3},BTIDNAME=\"P\";\n\n".format(mod,unt,su,su))

    
#****more trunk*****************************************************************************************
s=1
#dc=int(dch)+1

while(ws1.cell(row=7, column=s+2).value !=None):

    dc=ws1.cell(row=9, column=s+2).value
    lis = str(ws1.cell(row=7, column=s+2).value).split('-')
    ra = lis[0]
    se = lis[1]
    sl = lis[2]
    su = lis[3]

    lis = str(ws1.cell(row=8, column=s+2).value).split('-')
    mod = lis[0]
    unt = lis[1]
    
    #print(ra,se,sl,su,mod,unt,dc)
    
    print("MODIFY_DT_SUNIT:SUBSYSTEM=0,SUNITTYPE=97,Unit="+unt+",SUNIT="+su+",OFCNO="+tkg+",OFCNAME=\""+ofcname+"\",LINETYPE=0,Q50TAG=0,DCMEWORKMODE=0;")
    print("ADD_PRI_DCHANEL:DLINK=",dc,",MODULE=13,INFO=0,INFO1=2,DLINKNAME=\""+linkname+"\";")
    print("MODIFY_PHLK:LINK=",dc,",LINKTYPE=3,SUBSYSTEM=0,SPBUNIT=98,CPUID=2,TRKSUBSYS=0,TRKUNIT="+unt+",TRKE1="+su+",TRKSTARTTS=16,TSNUM=1,INFO=0,INFO1=2,COSPBUNIT=0,COCPUID=0,DLINKNAME=\""+linkname+"\";")
    print("ADD_LINKAS:LINKNO=",dc,",LINKTYPE=3,ASID=",asid,",LINKID=",dc,";")

    print("ASSIGN_TERMID:SUBSYSTEM=0,MODULE="+mod+",MGID=1,RESKIND=1,UNIT="+unt+",SUNIT_ST="+su+",SUNIT_END="+su+",BTIDNAME=\"P\";")

    f.write("MODIFY_DT_SUNIT:SUBSYSTEM=0,SUNITTYPE=97,Unit={},SUNIT={},OFCNO={},OFCNAME=\"{}\",LINETYPE=0,Q50TAG=0,DCMEWORKMODE=0;\n".format(unt,su,tkg,ofcname))
    f.write("ADD_PRI_DCHANEL:DLINK={},MODULE=13,INFO=0,INFO1=2,DLINKNAME=\"{}\";\n".format(dc,linkname))
    f.write("MODIFY_PHLK:LINK={},LINKTYPE=3,SUBSYSTEM=0,SPBUNIT=98,CPUID=2,TRKSUBSYS=0,TRKUNIT={},TRKE1={},TRKSTARTTS=16,TSNUM=1,INFO=0,INFO1=2,COSPBUNIT=0,COCPUID=0,DLINKNAME=\"{}\";\n".format(dc,unt,su,linkname))
    f.write("ADD_LINKAS:LINKNO={},LINKTYPE=3,ASID={},LINKID={};\n".format(dc,asid,dc))

    f.write("ASSIGN_TERMID:SUBSYSTEM=0,MODULE={},MGID=1,RESKIND=1,UNIT={},SUNIT_ST={},SUNIT_END={},BTIDNAME=\"P\";\n\n".format(mod,unt,su,su))


    #print("\n")
    #dc=dc+1
    s=s+1
#**********************************************************************************************    

#***SS*******************************************************************************

print("\n***********************************************************\n")
print("*          2- SS "+offname+"                                     *\n")
print("***********************************************************\n")


f.write("\n***********************************************************\n")
f.write("*          2- SS {}                                    *\n".format(offname))
f.write("***********************************************************\n\n")


#print("\n2-***** SS "+offname+"***************************************************\n")
#f.write("\n2-***** SS {} *****************************************************\n".format(offname))
    

print("CREATE_TGROUP:TGP_TYPE="+tkgtype+",TGROUP="+tkg+",LANGUAGE=3,REG=17,OFFICEID="+officeid+",CHANNEL=1,TRANSMISSION=3,NODEID="+nodeid+",LINE=35,FEETYPE=4,REMARK="+remark+",SENDNUMLEN=20;")
f.write("CREATE_TGROUP:TGP_TYPE={},TGROUP={},LANGUAGE=3,REG=17,OFFICEID={},CHANNEL=1,TRANSMISSION=3,NODEID={},LINE=35,FEETYPE=4,REMARK={},SENDNUMLEN=20;\n".format(tkgtype,tkg,officeid,nodeid,remark))
    
print("CREATE_PRITRKDVAL:NODEID="+nodeid+",DCHANNEL1="+dch+";")
print("CREATE_PRITRKDCH:NODEID="+nodeid+",TGROUP="+tkg+",DCHANNEL1="+dch+",DCHANNEL2="+dch+";")
print("CREATE_TRUNK:BCHANNEL=1,DCHANNEL="+dch+",TAG=0,PRIGROUP="+tkg+",UNOPEN=0,INDEX2=31,INDEX1=1,TGROUP="+tkg+";")
print("CREATE_TID_MASK:NODEID="+bignode+",NAME=\""+tidname+"\",TYPE=1,MASKTYPE=1,SUBNODE="+nodeid+",MASKVALUE1=31,GROUP="+tkg+",INDEX=1,MULTISEG=0;")
print("CREATE_TID_NAME:NODEID="+nodeid+",NAME=\""+tidname+"\",TYPE=1,GROUP="+tkg+",INDEX=1,NO1=1,NO2=31,PAD=5,TIDNO=;")
print("CREATE_ROUTE:ROUTE="+tkg+",TGROUP="+tkg+",REMARK=\""+linkname+"\",OPDDI=0,TPDDI=0,TPDDIFLAG=784,ORGTPDDI=0;")
print("CREATE_ROUTESET:ROUTESET="+tkg+",REMARK=\""+linkname+"\",ROUTEBYPER=0,ROUTEBYTG=0,ROUTEBYPDD=0,ROUTE1="+tkg+";")
print("CREATE_CHAIN:CHAIN="+tkg+",REMARK=\""+linkname+"\",ROUTESET1="+tkg+",TRFCCTRL=0;")
print("CREATE_CHAINSET:CHAINSET="+tkg+",REMARK=\""+linkname+"\",CHAIN1="+tkg+",CHAIN2=0,CHAIN3=0,CHAIN4=0,CHAIN5=0,CHAIN6=0,CHAIN7=0,CHAIN8=0,CHAIN9=0,CHAIN10=0,RUTANAIDX=,TAG=0,TURNSEL=0,CHOOSEBYPER=0;")
print("\n")

f.write("CREATE_PRITRKDVAL:NODEID={},DCHANNEL1={};\n".format(nodeid,dch))
f.write("CREATE_PRITRKDCH:NODEID={},TGROUP={},DCHANNEL1={},DCHANNEL2={};\n".format(nodeid,tkg,dch,dch))
f.write("CREATE_TRUNK:BCHANNEL=1,DCHANNEL={},TAG=0,PRIGROUP={},UNOPEN=0,INDEX2=31,INDEX1=1,TGROUP={};\n".format(dch,tkg,tkg))
f.write("CREATE_TID_MASK:NODEID={},NAME=\"{}\",TYPE=1,MASKTYPE=1,SUBNODE={},MASKVALUE1=31,GROUP={},INDEX=1,MULTISEG=0;\n".format(bignode,tidname,nodeid,tkg))
f.write("CREATE_TID_NAME:NODEID={},NAME=\"{}\",TYPE=1,GROUP={},INDEX=1,NO1=1,NO2=31,PAD=5,TIDNO=;\n".format(nodeid,tidname,tkg))
f.write("CREATE_ROUTE:ROUTE={},TGROUP={},REMARK=\"{}\",OPDDI=0,TPDDI=0,TPDDIFLAG=784,ORGTPDDI=0;\n".format(tkg,tkg,linkname))
f.write("CREATE_ROUTESET:ROUTESET={},REMARK=\"{}\",ROUTEBYPER=0,ROUTEBYTG=0,ROUTEBYPDD=0,ROUTE1={};\n".format(tkg,linkname,tkg))
f.write("CREATE_CHAIN:CHAIN={},REMARK=\"{}\",ROUTESET1={},TRFCCTRL=0;\n".format(tkg,linkname,tkg))
f.write("CREATE_CHAINSET:CHAINSET={},REMARK=\"{}\",CHAIN1={},CHAIN2=0,CHAIN3=0,CHAIN4=0,CHAIN5=0,CHAIN6=0,CHAIN7=0,CHAIN8=0,CHAIN9=0,CHAIN10=0,RUTANAIDX=,TAG=0,TURNSEL=0,CHOOSEBYPER=0;\n\n".format(tkg,linkname,tkg))

#print("CREATE_OUTGO_PQR:PQRS=\""+prf+"\",TREE="+tree+",NET=0,REL=3,CAT=3,NEWDAS=0,RESMAX="+max1+",RESMIN="+min1+",CHAINSET="+tkg+",SMSDN=0,CDN=0,OPTTAG=0,OPDDI=0,TPDDI=0,ORGTPDDI=0,NPPORTIN=0,OTHERSSP=0,BEEP=0,16KCBILL=0,16KCPULSE=0,IMPREST=0,IMPREST_HINT=0,TPDDIFLAG=784,COLORRINGDAS=0,OPHLRDDI=0,TPHLRDDI=0,RDTHLRDDI=0,HLRDDITAG=0,ANAEND=1,CIC=0,CALLSCOPE=1,CC=98,AC=31,MONFLAG=0,GCRTONEID=0,SRVTONENO=0,SRVCAUVAL=0,AISUPPORT=0,OUTERSSP=0,TIMEOUTALARM=0,BROKENLINE=1,MAXCALLTIME=9000,FOLLOWDAS=0,CINTGROUP=0,REDIRECTRN=0,BTYPE=0,SRVSHIELD=0;")

#f.write("CREATE_OUTGO_PQR:PQRS=\"{}\",TREE={},NET=0,REL=3,CAT=3,NEWDAS=0,RESMAX={},RESMIN={},CHAINSET={},SMSDN=0,CDN=0,OPTTAG=0,OPDDI=0,TPDDI=0,ORGTPDDI=0,NPPORTIN=0,OTHERSSP=0,BEEP=0,16KCBILL=0,16KCPULSE=0,IMPREST=0,IMPREST_HINT=0,TPDDIFLAG=784,COLORRINGDAS=0,OPHLRDDI=0,TPHLRDDI=0,RDTHLRDDI=0,HLRDDITAG=0,ANAEND=1,CIC=0,CALLSCOPE=1,CC=98,AC=31,MONFLAG=0,GCRTONEID=0,SRVTONENO=0,SRVCAUVAL=0,AISUPPORT=0,OUTERSSP=0,TIMEOUTALARM=0,BROKENLINE=1,MAXCALLTIME=9000,FOLLOWDAS=0,CINTGROUP=0,REDIRECTRN=0,BTYPE=0,SRVSHIELD=0;\n".format(prf,tree,max1,min1,tkg))
    
if (int(office)==0):

    print("CREATE_OUTGO_PQR:PQRS=\""+prf+"\",TREE=1,NET=0,REL=3,CAT=3,NEWDAS=0,RESMAX="+max1+",RESMIN="+min1+",CHAINSET="+tkg+",SMSDN=0,CDN=0,OPTTAG=0,OPDDI=0,TPDDI=0,ORGTPDDI=0,NPPORTIN=0,OTHERSSP=0,BEEP=0,16KCBILL=0,16KCPULSE=0,IMPREST=0,IMPREST_HINT=0,TPDDIFLAG=784,COLORRINGDAS=0,OPHLRDDI=0,TPHLRDDI=0,RDTHLRDDI=0,HLRDDITAG=0,ANAEND=1,CIC=0,CALLSCOPE=1,CC=98,AC=31,MONFLAG=0,GCRTONEID=0,SRVTONENO=0,SRVCAUVAL=0,AISUPPORT=0,OUTERSSP=0,TIMEOUTALARM=0,BROKENLINE=1,MAXCALLTIME=9000,FOLLOWDAS=0,CINTGROUP=0,REDIRECTRN=0,BTYPE=0,SRVSHIELD=0;")
    print("CREATE_OUTGO_PQR:PQRS=\""+prf+"\",TREE=100,NET=0,REL=3,CAT=3,NEWDAS=0,RESMAX="+max1+",RESMIN="+min1+",CHAINSET="+tkg+",SMSDN=0,CDN=0,OPTTAG=0,OPDDI=0,TPDDI=0,ORGTPDDI=0,NPPORTIN=0,OTHERSSP=0,BEEP=0,16KCBILL=0,16KCPULSE=0,IMPREST=0,IMPREST_HINT=0,TPDDIFLAG=784,COLORRINGDAS=0,OPHLRDDI=0,TPHLRDDI=0,RDTHLRDDI=0,HLRDDITAG=0,ANAEND=1,CIC=0,CALLSCOPE=1,CC=98,AC=31,MONFLAG=0,GCRTONEID=0,SRVTONENO=0,SRVCAUVAL=0,AISUPPORT=0,OUTERSSP=0,TIMEOUTALARM=0,BROKENLINE=1,MAXCALLTIME=9000,FOLLOWDAS=0,CINTGROUP=0,REDIRECTRN=0,BTYPE=0,SRVSHIELD=0;")
    print("CREATE_OUTGO_PQR:PQRS=\""+prf+"\",TREE=802,NET=0,REL=3,CAT=3,NEWDAS=0,RESMAX="+max1+",RESMIN="+min1+",CHAINSET="+tkg+",SMSDN=0,CDN=0,OPTTAG=0,OPDDI=0,TPDDI=0,ORGTPDDI=0,NPPORTIN=0,OTHERSSP=0,BEEP=0,16KCBILL=0,16KCPULSE=0,IMPREST=0,IMPREST_HINT=0,TPDDIFLAG=784,COLORRINGDAS=0,OPHLRDDI=0,TPHLRDDI=0,RDTHLRDDI=0,HLRDDITAG=0,ANAEND=1,CIC=0,CALLSCOPE=1,CC=98,AC=31,MONFLAG=0,GCRTONEID=0,SRVTONENO=0,SRVCAUVAL=0,AISUPPORT=0,OUTERSSP=0,TIMEOUTALARM=0,BROKENLINE=1,MAXCALLTIME=9000,FOLLOWDAS=0,CINTGROUP=0,REDIRECTRN=0,BTYPE=0,SRVSHIELD=0;")
    print("CREATE_OUTGO_PQR:PQRS=\""+prf+"\",TREE=804,NET=0,REL=3,CAT=3,NEWDAS=0,RESMAX="+max1+",RESMIN="+min1+",CHAINSET="+tkg+",SMSDN=0,CDN=0,OPTTAG=0,OPDDI=0,TPDDI=0,ORGTPDDI=0,NPPORTIN=0,OTHERSSP=0,BEEP=0,16KCBILL=0,16KCPULSE=0,IMPREST=0,IMPREST_HINT=0,TPDDIFLAG=784,COLORRINGDAS=0,OPHLRDDI=0,TPHLRDDI=0,RDTHLRDDI=0,HLRDDITAG=0,ANAEND=1,CIC=0,CALLSCOPE=1,CC=98,AC=31,MONFLAG=0,GCRTONEID=0,SRVTONENO=0,SRVCAUVAL=0,AISUPPORT=0,OUTERSSP=0,TIMEOUTALARM=0,BROKENLINE=1,MAXCALLTIME=9000,FOLLOWDAS=0,CINTGROUP=0,REDIRECTRN=0,BTYPE=0,SRVSHIELD=0;")
    print("\n")

    f.write("CREATE_OUTGO_PQR:PQRS=\"{}\",TREE=1,NET=0,REL=3,CAT=3,NEWDAS=0,RESMAX={},RESMIN={},CHAINSET={},SMSDN=0,CDN=0,OPTTAG=0,OPDDI=0,TPDDI=0,ORGTPDDI=0,NPPORTIN=0,OTHERSSP=0,BEEP=0,16KCBILL=0,16KCPULSE=0,IMPREST=0,IMPREST_HINT=0,TPDDIFLAG=784,COLORRINGDAS=0,OPHLRDDI=0,TPHLRDDI=0,RDTHLRDDI=0,HLRDDITAG=0,ANAEND=1,CIC=0,CALLSCOPE=1,CC=98,AC=31,MONFLAG=0,GCRTONEID=0,SRVTONENO=0,SRVCAUVAL=0,AISUPPORT=0,OUTERSSP=0,TIMEOUTALARM=0,BROKENLINE=1,MAXCALLTIME=9000,FOLLOWDAS=0,CINTGROUP=0,REDIRECTRN=0,BTYPE=0,SRVSHIELD=0;\n".format(prf,max1,min1,tkg))
    f.write("CREATE_OUTGO_PQR:PQRS=\"{}\",TREE=100,NET=0,REL=3,CAT=3,NEWDAS=0,RESMAX={},RESMIN={},CHAINSET={},SMSDN=0,CDN=0,OPTTAG=0,OPDDI=0,TPDDI=0,ORGTPDDI=0,NPPORTIN=0,OTHERSSP=0,BEEP=0,16KCBILL=0,16KCPULSE=0,IMPREST=0,IMPREST_HINT=0,TPDDIFLAG=784,COLORRINGDAS=0,OPHLRDDI=0,TPHLRDDI=0,RDTHLRDDI=0,HLRDDITAG=0,ANAEND=1,CIC=0,CALLSCOPE=1,CC=98,AC=31,MONFLAG=0,GCRTONEID=0,SRVTONENO=0,SRVCAUVAL=0,AISUPPORT=0,OUTERSSP=0,TIMEOUTALARM=0,BROKENLINE=1,MAXCALLTIME=9000,FOLLOWDAS=0,CINTGROUP=0,REDIRECTRN=0,BTYPE=0,SRVSHIELD=0;\n".format(prf,max1,min1,tkg))
    f.write("CREATE_OUTGO_PQR:PQRS=\"{}\",TREE=802,NET=0,REL=3,CAT=3,NEWDAS=0,RESMAX={},RESMIN={},CHAINSET={},SMSDN=0,CDN=0,OPTTAG=0,OPDDI=0,TPDDI=0,ORGTPDDI=0,NPPORTIN=0,OTHERSSP=0,BEEP=0,16KCBILL=0,16KCPULSE=0,IMPREST=0,IMPREST_HINT=0,TPDDIFLAG=784,COLORRINGDAS=0,OPHLRDDI=0,TPHLRDDI=0,RDTHLRDDI=0,HLRDDITAG=0,ANAEND=1,CIC=0,CALLSCOPE=1,CC=98,AC=31,MONFLAG=0,GCRTONEID=0,SRVTONENO=0,SRVCAUVAL=0,AISUPPORT=0,OUTERSSP=0,TIMEOUTALARM=0,BROKENLINE=1,MAXCALLTIME=9000,FOLLOWDAS=0,CINTGROUP=0,REDIRECTRN=0,BTYPE=0,SRVSHIELD=0;\n".format(prf,max1,min1,tkg))
    f.write("CREATE_OUTGO_PQR:PQRS=\"{}\",TREE=804,NET=0,REL=3,CAT=3,NEWDAS=0,RESMAX={},RESMIN={},CHAINSET={},SMSDN=0,CDN=0,OPTTAG=0,OPDDI=0,TPDDI=0,ORGTPDDI=0,NPPORTIN=0,OTHERSSP=0,BEEP=0,16KCBILL=0,16KCPULSE=0,IMPREST=0,IMPREST_HINT=0,TPDDIFLAG=784,COLORRINGDAS=0,OPHLRDDI=0,TPHLRDDI=0,RDTHLRDDI=0,HLRDDITAG=0,ANAEND=1,CIC=0,CALLSCOPE=1,CC=98,AC=31,MONFLAG=0,GCRTONEID=0,SRVTONENO=0,SRVCAUVAL=0,AISUPPORT=0,OUTERSSP=0,TIMEOUTALARM=0,BROKENLINE=1,MAXCALLTIME=9000,FOLLOWDAS=0,CINTGROUP=0,REDIRECTRN=0,BTYPE=0,SRVSHIELD=0;\n\n".format(prf,max1,min1,tkg))

else:

    print("CREATE_OUTGO_PQR:PQRS=\""+prf+"\",TREE=200,NET=0,REL=3,CAT=3,NEWDAS=0,RESMAX="+max1+",RESMIN="+min1+",CHAINSET="+tkg+",SMSDN=0,CDN=0,OPTTAG=0,OPDDI=0,TPDDI=0,ORGTPDDI=0,NPPORTIN=0,OTHERSSP=0,BEEP=0,16KCBILL=0,16KCPULSE=0,IMPREST=0,IMPREST_HINT=0,TPDDIFLAG=784,COLORRINGDAS=0,OPHLRDDI=0,TPHLRDDI=0,RDTHLRDDI=0,HLRDDITAG=0,ANAEND=1,CIC=0,CALLSCOPE=1,CC=98,AC=31,MONFLAG=0,GCRTONEID=0,SRVTONENO=0,SRVCAUVAL=0,AISUPPORT=0,OUTERSSP=0,TIMEOUTALARM=0,BROKENLINE=1,MAXCALLTIME=9000,FOLLOWDAS=0,CINTGROUP=0,REDIRECTRN=0,BTYPE=0,SRVSHIELD=0;")
    print("CREATE_OUTGO_PQR:PQRS=\""+prf+"\",TREE=201,NET=0,REL=3,CAT=3,NEWDAS=0,RESMAX="+max1+",RESMIN="+min1+",CHAINSET="+tkg+",SMSDN=0,CDN=0,OPTTAG=0,OPDDI=0,TPDDI=0,ORGTPDDI=0,NPPORTIN=0,OTHERSSP=0,BEEP=0,16KCBILL=0,16KCPULSE=0,IMPREST=0,IMPREST_HINT=0,TPDDIFLAG=784,COLORRINGDAS=0,OPHLRDDI=0,TPHLRDDI=0,RDTHLRDDI=0,HLRDDITAG=0,ANAEND=1,CIC=0,CALLSCOPE=1,CC=98,AC=31,MONFLAG=0,GCRTONEID=0,SRVTONENO=0,SRVCAUVAL=0,AISUPPORT=0,OUTERSSP=0,TIMEOUTALARM=0,BROKENLINE=1,MAXCALLTIME=9000,FOLLOWDAS=0,CINTGROUP=0,REDIRECTRN=0,BTYPE=0,SRVSHIELD=0;")
    
    f.write("CREATE_OUTGO_PQR:PQRS=\"{}\",TREE=200,NET=0,REL=3,CAT=3,NEWDAS=0,RESMAX={},RESMIN={},CHAINSET={},SMSDN=0,CDN=0,OPTTAG=0,OPDDI=0,TPDDI=0,ORGTPDDI=0,NPPORTIN=0,OTHERSSP=0,BEEP=0,16KCBILL=0,16KCPULSE=0,IMPREST=0,IMPREST_HINT=0,TPDDIFLAG=784,COLORRINGDAS=0,OPHLRDDI=0,TPHLRDDI=0,RDTHLRDDI=0,HLRDDITAG=0,ANAEND=1,CIC=0,CALLSCOPE=1,CC=98,AC=31,MONFLAG=0,GCRTONEID=0,SRVTONENO=0,SRVCAUVAL=0,AISUPPORT=0,OUTERSSP=0,TIMEOUTALARM=0,BROKENLINE=1,MAXCALLTIME=9000,FOLLOWDAS=0,CINTGROUP=0,REDIRECTRN=0,BTYPE=0,SRVSHIELD=0;\n".format(prf,max1,min1,tkg))
    f.write("CREATE_OUTGO_PQR:PQRS=\"{}\",TREE=201,NET=0,REL=3,CAT=3,NEWDAS=0,RESMAX={},RESMIN={},CHAINSET={},SMSDN=0,CDN=0,OPTTAG=0,OPDDI=0,TPDDI=0,ORGTPDDI=0,NPPORTIN=0,OTHERSSP=0,BEEP=0,16KCBILL=0,16KCPULSE=0,IMPREST=0,IMPREST_HINT=0,TPDDIFLAG=784,COLORRINGDAS=0,OPHLRDDI=0,TPHLRDDI=0,RDTHLRDDI=0,HLRDDITAG=0,ANAEND=1,CIC=0,CALLSCOPE=1,CC=98,AC=31,MONFLAG=0,GCRTONEID=0,SRVTONENO=0,SRVCAUVAL=0,AISUPPORT=0,OUTERSSP=0,TIMEOUTALARM=0,BROKENLINE=1,MAXCALLTIME=9000,FOLLOWDAS=0,CINTGROUP=0,REDIRECTRN=0,BTYPE=0,SRVSHIELD=0;\n".format(prf,max1,min1,tkg))


print("CREATE_TREE:TREE="+tkg+",NET=1,COPYTREE="+copytree+",MODE=1;")
print("DELETE_PQR:TREE="+tkg+",PQRS=\""+delprf+"\";")

f.write("CREATE_TREE:TREE={},NET=1,COPYTREE={},MODE=1;\n".format(tkg,copytree))
f.write("DELETE_PQR:TREE={},PQRS=\"{}\";\n".format(tkg,delprf))


#print("CREATE_OP_PQR:PQRS=\""+callid+"\",TREE="+tkg+",CAT=31,ANAEND=1,NEWDAS="+newdas+",NETATTR=1,OPDDI=0,ORGTPDDI=0,TPDDI=0,OPHLRDDI=0,TPHLRDDI=0,RDTHLRDDI=0,HLRDDITAG=0,OPTTAG=0,ISLOCAL=0,AISUPPORT=0,RESMAX="+max2+",RESMIN="+min2+",MAXFAILIDX=1,MINFAILIDX=1,BEEP=0,TPDDIFLAG=784;")
#f.write("CREATE_OP_PQR:PQRS=\"{}\",TREE={},CAT=31,ANAEND=1,NEWDAS={},NETATTR=1,OPDDI=0,ORGTPDDI=0,TPDDI=0,OPHLRDDI=0,TPHLRDDI=0,RDTHLRDDI=0,HLRDDITAG=0,OPTTAG=0,ISLOCAL=0,AISUPPORT=0,RESMAX={},RESMIN={},MAXFAILIDX=1,MINFAILIDX=1,BEEP=0,TPDDIFLAG=784;\n".format(callid,tkg,newdas,max2,min2))


if(int(tkgtype)!=2): #not outgoing 

    print("CREATE_OP_PQR:PQRS=\""+callid+"\",TREE="+tkg+",CAT=31,ANAEND=1,NEWDAS="+newdas+",NETATTR=1,OPDDI=0,ORGTPDDI=0,TPDDI=0,OPHLRDDI=0,TPHLRDDI=0,RDTHLRDDI=0,HLRDDITAG=0,OPTTAG=0,ISLOCAL=0,AISUPPORT=0,RESMAX="+max2+",RESMIN="+min2+",MAXFAILIDX=1,MINFAILIDX=1,BEEP=0,TPDDIFLAG=784;")

    print("CREATE_DAS:DAS="+tkg+",PRESETNET=0,PRIVATE="+tkg+",REMARK=\""+linkname+"\";")
    print("MODIFY_TGROUP:OPDAS="+tkg+",RIGHTMOD=3,TGROUP="+tkg+";")
    print("\n")

    f.write("CREATE_OP_PQR:PQRS=\"{}\",TREE={},CAT=31,ANAEND=1,NEWDAS={},NETATTR=1,OPDDI=0,ORGTPDDI=0,TPDDI=0,OPHLRDDI=0,TPHLRDDI=0,RDTHLRDDI=0,HLRDDITAG=0,OPTTAG=0,ISLOCAL=0,AISUPPORT=0,RESMAX={},RESMIN={},MAXFAILIDX=1,MINFAILIDX=1,BEEP=0,TPDDIFLAG=784;\n".format(callid,tkg,newdas,max2,min2))
    f.write("CREATE_DAS:DAS={},PRESETNET=0,PRIVATE={},REMARK=\"{}\";\n".format(tkg,tkg,linkname))
    f.write("MODIFY_TGROUP:OPDAS={},RIGHTMOD=3,TGROUP={};\n\n".format(tkg,tkg))


# MODIFY_TGROUP:RIGHTMOD=3,TGROUP=393; #

#********************************************************************************************
#****more trunk*****************************************************************************************
s=1
#dc=int(dch)+1
ind=33
while(ws1.cell(row=7, column=s+2).value !=None):

    dc=ws1.cell(row=9, column=s+2).value

    lis = str(ws1.cell(row=7, column=s+2).value).split('-')
    ra = lis[0]
    se = lis[1]
    sl = lis[2]
    su = lis[3]

    lis = str(ws1.cell(row=8, column=s+2).value).split('-')
    mod = lis[0]
    unt = lis[1]
    tidname='P'+("000"+mod)[-3:]+"00000"+("000"+unt)[-3:]+("000"+su)[-3:]
    
    #print(ra,se,sl,su,mod,unt,dc,tidname)
    

    print("CREATE_PRITRKDVAL:NODEID="+nodeid+",DCHANNEL1=",dc,";")
    print("CREATE_PRITRKDCH:NODEID="+nodeid+",TGROUP="+tkg+",DCHANNEL1=",dc,",DCHANNEL2=",dc,";")
    print("CREATE_TRUNK:BCHANNEL=1,DCHANNEL=",dc,",TAG=0,PRIGROUP="+tkg+",UNOPEN=0,INDEX2=",ind+30,",INDEX1=",ind,",TGROUP="+tkg+";")

    print("CREATE_TID_MASK:NODEID="+bignode+",NAME=\""+tidname+"\",TYPE=1,MASKTYPE=1,SUBNODE="+nodeid+",MASKVALUE1=31,GROUP="+tkg+",INDEX=",ind,",MULTISEG=0;")
    print("CREATE_TID_NAME:NODEID="+nodeid+",NAME=\""+tidname+"\",TYPE=1,GROUP="+tkg+",INDEX=",ind,",NO1=1,NO2=31,PAD=5,TIDNO=;")

    f.write("CREATE_PRITRKDVAL:NODEID={},DCHANNEL1={};\n".format(nodeid,dc))
    f.write("CREATE_PRITRKDCH:NODEID={},TGROUP={},DCHANNEL1={},DCHANNEL2={};\n".format(nodeid,tkg,dc,dc))
    f.write("CREATE_TRUNK:BCHANNEL=1,DCHANNEL={},TAG=0,PRIGROUP={},UNOPEN=0,INDEX2={},INDEX1={},TGROUP={};\n".format(dc,tkg,ind+30,ind,tkg))

    f.write("CREATE_TID_MASK:NODEID={},NAME=\"{}\",TYPE=1,MASKTYPE=1,SUBNODE={},MASKVALUE1=31,GROUP={},INDEX={},MULTISEG=0;\n".format(bignode,tidname,nodeid,tkg,ind))
    f.write("CREATE_TID_NAME:NODEID={},NAME=\"{}\",TYPE=1,GROUP={},INDEX={},NO1=1,NO2=31,PAD=5,TIDNO=;\n".format(nodeid,tidname,tkg,ind))

    #print("\n")
    ind=ind+32
 #   dc=dc+1
    s=s+1
#**********************************************************************************************    
#*** SS other exchange *******************************************************************************

if (int(office)==1):
#    print("\n3-***** Other SS FEYZ***************************************************\n")
#    f.write("\n3-***** Other SS FEYZ***************************************************\n\n")


    print("\n***********************************************************\n")
    print("*          3- Other SS FEYZ                               *\n")
    print("***********************************************************\n")

    f.write("\n***********************************************************\n")
    f.write("*          3- Other SS FEYZ                               *\n")
    f.write("***********************************************************\n\n")

    
    print("CREATE_OUTGO_PQR:PQRS=\""+prf+"\",TREE=1,NET=0,REL=3,CAT=3,NEWDAS=0,RESMAX="+max1+",RESMIN="+min1+",CHAINSET=2,SMSDN=0,CDN=0,OPTTAG=0,OPDDI=0,TPDDI=0,ORGTPDDI=0,NPPORTIN=0,OTHERSSP=0,BEEP=0,16KCBILL=0,16KCPULSE=0,IMPREST=0,IMPREST_HINT=0,TPDDIFLAG=784,COLORRINGDAS=0,OPHLRDDI=0,TPHLRDDI=0,RDTHLRDDI=0,HLRDDITAG=0,ANAEND=1,CIC=0,CALLSCOPE=1,CC=98,AC=31,MONFLAG=0,GCRTONEID=0,SRVTONENO=0,SRVCAUVAL=0,AISUPPORT=0,OUTERSSP=0,TIMEOUTALARM=0,BROKENLINE=1,MAXCALLTIME=9000,FOLLOWDAS=0,CINTGROUP=0,REDIRECTRN=0,BTYPE=0,SRVSHIELD=0;")
    print("CREATE_OUTGO_PQR:PQRS=\""+prf+"\",TREE=100,NET=0,REL=3,CAT=3,NEWDAS=0,RESMAX="+max1+",RESMIN="+min1+",CHAINSET=2,SMSDN=0,CDN=0,OPTTAG=0,OPDDI=0,TPDDI=0,ORGTPDDI=0,NPPORTIN=0,OTHERSSP=0,BEEP=0,16KCBILL=0,16KCPULSE=0,IMPREST=0,IMPREST_HINT=0,TPDDIFLAG=784,COLORRINGDAS=0,OPHLRDDI=0,TPHLRDDI=0,RDTHLRDDI=0,HLRDDITAG=0,ANAEND=1,CIC=0,CALLSCOPE=1,CC=98,AC=31,MONFLAG=0,GCRTONEID=0,SRVTONENO=0,SRVCAUVAL=0,AISUPPORT=0,OUTERSSP=0,TIMEOUTALARM=0,BROKENLINE=1,MAXCALLTIME=9000,FOLLOWDAS=0,CINTGROUP=0,REDIRECTRN=0,BTYPE=0,SRVSHIELD=0;")
    print("CREATE_OUTGO_PQR:PQRS=\""+prf+"\",TREE=802,NET=0,REL=3,CAT=3,NEWDAS=0,RESMAX="+max1+",RESMIN="+min1+",CHAINSET=2,SMSDN=0,CDN=0,OPTTAG=0,OPDDI=0,TPDDI=0,ORGTPDDI=0,NPPORTIN=0,OTHERSSP=0,BEEP=0,16KCBILL=0,16KCPULSE=0,IMPREST=0,IMPREST_HINT=0,TPDDIFLAG=784,COLORRINGDAS=0,OPHLRDDI=0,TPHLRDDI=0,RDTHLRDDI=0,HLRDDITAG=0,ANAEND=1,CIC=0,CALLSCOPE=1,CC=98,AC=31,MONFLAG=0,GCRTONEID=0,SRVTONENO=0,SRVCAUVAL=0,AISUPPORT=0,OUTERSSP=0,TIMEOUTALARM=0,BROKENLINE=1,MAXCALLTIME=9000,FOLLOWDAS=0,CINTGROUP=0,REDIRECTRN=0,BTYPE=0,SRVSHIELD=0;")
    print("CREATE_OUTGO_PQR:PQRS=\""+prf+"\",TREE=804,NET=0,REL=3,CAT=3,NEWDAS=0,RESMAX="+max1+",RESMIN="+min1+",CHAINSET=2,SMSDN=0,CDN=0,OPTTAG=0,OPDDI=0,TPDDI=0,ORGTPDDI=0,NPPORTIN=0,OTHERSSP=0,BEEP=0,16KCBILL=0,16KCPULSE=0,IMPREST=0,IMPREST_HINT=0,TPDDIFLAG=784,COLORRINGDAS=0,OPHLRDDI=0,TPHLRDDI=0,RDTHLRDDI=0,HLRDDITAG=0,ANAEND=1,CIC=0,CALLSCOPE=1,CC=98,AC=31,MONFLAG=0,GCRTONEID=0,SRVTONENO=0,SRVCAUVAL=0,AISUPPORT=0,OUTERSSP=0,TIMEOUTALARM=0,BROKENLINE=1,MAXCALLTIME=9000,FOLLOWDAS=0,CINTGROUP=0,REDIRECTRN=0,BTYPE=0,SRVSHIELD=0;\n\n")

    f.write("CREATE_OUTGO_PQR:PQRS=\"{}\",TREE=1,NET=0,REL=3,CAT=3,NEWDAS=0,RESMAX={},RESMIN={},CHAINSET=2,SMSDN=0,CDN=0,OPTTAG=0,OPDDI=0,TPDDI=0,ORGTPDDI=0,NPPORTIN=0,OTHERSSP=0,BEEP=0,16KCBILL=0,16KCPULSE=0,IMPREST=0,IMPREST_HINT=0,TPDDIFLAG=784,COLORRINGDAS=0,OPHLRDDI=0,TPHLRDDI=0,RDTHLRDDI=0,HLRDDITAG=0,ANAEND=1,CIC=0,CALLSCOPE=1,CC=98,AC=31,MONFLAG=0,GCRTONEID=0,SRVTONENO=0,SRVCAUVAL=0,AISUPPORT=0,OUTERSSP=0,TIMEOUTALARM=0,BROKENLINE=1,MAXCALLTIME=9000,FOLLOWDAS=0,CINTGROUP=0,REDIRECTRN=0,BTYPE=0,SRVSHIELD=0;\n".format(prf,max1,min1))
    f.write("CREATE_OUTGO_PQR:PQRS=\"{}\",TREE=100,NET=0,REL=3,CAT=3,NEWDAS=0,RESMAX={},RESMIN={},CHAINSET=2,SMSDN=0,CDN=0,OPTTAG=0,OPDDI=0,TPDDI=0,ORGTPDDI=0,NPPORTIN=0,OTHERSSP=0,BEEP=0,16KCBILL=0,16KCPULSE=0,IMPREST=0,IMPREST_HINT=0,TPDDIFLAG=784,COLORRINGDAS=0,OPHLRDDI=0,TPHLRDDI=0,RDTHLRDDI=0,HLRDDITAG=0,ANAEND=1,CIC=0,CALLSCOPE=1,CC=98,AC=31,MONFLAG=0,GCRTONEID=0,SRVTONENO=0,SRVCAUVAL=0,AISUPPORT=0,OUTERSSP=0,TIMEOUTALARM=0,BROKENLINE=1,MAXCALLTIME=9000,FOLLOWDAS=0,CINTGROUP=0,REDIRECTRN=0,BTYPE=0,SRVSHIELD=0;\n".format(prf,max1,min1))
    f.write("CREATE_OUTGO_PQR:PQRS=\"{}\",TREE=802,NET=0,REL=3,CAT=3,NEWDAS=0,RESMAX={},RESMIN={},CHAINSET=2,SMSDN=0,CDN=0,OPTTAG=0,OPDDI=0,TPDDI=0,ORGTPDDI=0,NPPORTIN=0,OTHERSSP=0,BEEP=0,16KCBILL=0,16KCPULSE=0,IMPREST=0,IMPREST_HINT=0,TPDDIFLAG=784,COLORRINGDAS=0,OPHLRDDI=0,TPHLRDDI=0,RDTHLRDDI=0,HLRDDITAG=0,ANAEND=1,CIC=0,CALLSCOPE=1,CC=98,AC=31,MONFLAG=0,GCRTONEID=0,SRVTONENO=0,SRVCAUVAL=0,AISUPPORT=0,OUTERSSP=0,TIMEOUTALARM=0,BROKENLINE=1,MAXCALLTIME=9000,FOLLOWDAS=0,CINTGROUP=0,REDIRECTRN=0,BTYPE=0,SRVSHIELD=0;\n".format(prf,max1,min1))
    f.write("CREATE_OUTGO_PQR:PQRS=\"{}\",TREE=804,NET=0,REL=3,CAT=3,NEWDAS=0,RESMAX={},RESMIN={},CHAINSET=2,SMSDN=0,CDN=0,OPTTAG=0,OPDDI=0,TPDDI=0,ORGTPDDI=0,NPPORTIN=0,OTHERSSP=0,BEEP=0,16KCBILL=0,16KCPULSE=0,IMPREST=0,IMPREST_HINT=0,TPDDIFLAG=784,COLORRINGDAS=0,OPHLRDDI=0,TPHLRDDI=0,RDTHLRDDI=0,HLRDDITAG=0,ANAEND=1,CIC=0,CALLSCOPE=1,CC=98,AC=31,MONFLAG=0,GCRTONEID=0,SRVTONENO=0,SRVCAUVAL=0,AISUPPORT=0,OUTERSSP=0,TIMEOUTALARM=0,BROKENLINE=1,MAXCALLTIME=9000,FOLLOWDAS=0,CINTGROUP=0,REDIRECTRN=0,BTYPE=0,SRVSHIELD=0;\n\n\n".format(prf,max1,min1))

if (int(office)==0):
#    print("\n3-***** Other SS KHARAZI***************************************************\n")
#    f.write("\n3-***** Other SS KHARAZI***************************************************\n")
    
    print("\n***********************************************************\n")
    print("*          3- Other SS KHARAZI                            *\n")
    print("***********************************************************\n")

    f.write("\n***********************************************************\n")
    f.write("*          3- Other SS KHARAZI                           *\n")
    f.write("***********************************************************\n\n")


    print("CREATE_OUTGO_PQR:PQRS=\""+prf+"\",TREE=200,NET=1,REL=3,CAT=3,NEWDAS=0,RESMAX="+max1+",RESMIN="+min1+",CHAINSET=201,SMSDN=0,CDN=0,OPTTAG=0,OPDDI=0,TPDDI=0,ORGTPDDI=0,NPPORTIN=0,OTHERSSP=0,BEEP=0,16KCBILL=0,16KCPULSE=0,IMPREST=0,IMPREST_HINT=0,TPDDIFLAG=784,COLORRINGDAS=0,OPHLRDDI=0,TPHLRDDI=0,RDTHLRDDI=0,HLRDDITAG=0,ANAEND=1,CIC=0,CALLSCOPE=1,CC=98,AC=31,MONFLAG=0,GCRTONEID=0,SRVTONENO=0,SRVCAUVAL=0,AISUPPORT=0,OUTERSSP=0,TIMEOUTALARM=0,BROKENLINE=1,MAXCALLTIME=9000,FOLLOWDAS=0,CINTGROUP=0,REDIRECTRN=0,BTYPE=0,SRVSHIELD=0;\n\n\n")
    print("CREATE_OUTGO_PQR:PQRS=\""+prf+"\",TREE=201,NET=1,REL=3,CAT=3,NEWDAS=0,RESMAX="+max1+",RESMIN="+min1+",CHAINSET=201,SMSDN=0,CDN=0,OPTTAG=0,OPDDI=0,TPDDI=0,ORGTPDDI=0,NPPORTIN=0,OTHERSSP=0,BEEP=0,16KCBILL=0,16KCPULSE=0,IMPREST=0,IMPREST_HINT=0,TPDDIFLAG=784,COLORRINGDAS=0,OPHLRDDI=0,TPHLRDDI=0,RDTHLRDDI=0,HLRDDITAG=0,ANAEND=1,CIC=0,CALLSCOPE=1,CC=98,AC=31,MONFLAG=0,GCRTONEID=0,SRVTONENO=0,SRVCAUVAL=0,AISUPPORT=0,OUTERSSP=0,TIMEOUTALARM=0,BROKENLINE=1,MAXCALLTIME=9000,FOLLOWDAS=0,CINTGROUP=0,REDIRECTRN=0,BTYPE=0,SRVSHIELD=0;\n\n\n")

    f.write("CREATE_OUTGO_PQR:PQRS=\"{}\",TREE=200,NET=1,REL=3,CAT=3,NEWDAS=0,RESMAX={},RESMIN={},CHAINSET=201,SMSDN=0,CDN=0,OPTTAG=0,OPDDI=0,TPDDI=0,ORGTPDDI=0,NPPORTIN=0,OTHERSSP=0,BEEP=0,16KCBILL=0,16KCPULSE=0,IMPREST=0,IMPREST_HINT=0,TPDDIFLAG=784,COLORRINGDAS=0,OPHLRDDI=0,TPHLRDDI=0,RDTHLRDDI=0,HLRDDITAG=0,ANAEND=1,CIC=0,CALLSCOPE=1,CC=98,AC=31,MONFLAG=0,GCRTONEID=0,SRVTONENO=0,SRVCAUVAL=0,AISUPPORT=0,OUTERSSP=0,TIMEOUTALARM=0,BROKENLINE=1,MAXCALLTIME=9000,FOLLOWDAS=0,CINTGROUP=0,REDIRECTRN=0,BTYPE=0,SRVSHIELD=0;\n\n\n".format(prf,max1,min1))
    f.write("CREATE_OUTGO_PQR:PQRS=\"{}\",TREE=201,NET=1,REL=3,CAT=3,NEWDAS=0,RESMAX={},RESMIN={},CHAINSET=201,SMSDN=0,CDN=0,OPTTAG=0,OPDDI=0,TPDDI=0,ORGTPDDI=0,NPPORTIN=0,OTHERSSP=0,BEEP=0,16KCBILL=0,16KCPULSE=0,IMPREST=0,IMPREST_HINT=0,TPDDIFLAG=784,COLORRINGDAS=0,OPHLRDDI=0,TPHLRDDI=0,RDTHLRDDI=0,HLRDDITAG=0,ANAEND=1,CIC=0,CALLSCOPE=1,CC=98,AC=31,MONFLAG=0,GCRTONEID=0,SRVTONENO=0,SRVCAUVAL=0,AISUPPORT=0,OUTERSSP=0,TIMEOUTALARM=0,BROKENLINE=1,MAXCALLTIME=9000,FOLLOWDAS=0,CINTGROUP=0,REDIRECTRN=0,BTYPE=0,SRVSHIELD=0;\n\n\n".format(prf,max1,min1))



f.close()
